### PR TITLE
Item/azurefunctions dbcontext sample

### PR DESCRIPTION
**Pull request by koskila**
Adds another sample I was recently working on - a simple dbcontext injection for an azure function app :)

Hope it's useful!

### CODE REVIEW

**Comment by koskila** [comment]
Okay, about the sample count. It was 319 before my 1 sample. I calculated the number of samples in the TOC (+ .NET 5), and it was 323 after I added one sample (so I guess someone had missed incrementing the total). However,  someone had committed one more sample taking the sample count from 319 -> 320 while I was working on this, so I think the count should now be 324.

**Comment by dodyg** [comment]
Noted. I will do revise everything this weekend. Thank you for the pull request.

**Comment by dodyg** [comment]
Can you please add a readme on the https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/azure-functions folder so that it easier to point people to Azure specific samples?

Please also tag yourself in the readme. I want to make sure everyone contributing samples gets appropriate credit.

**Comment by koskila** [comment]
Thanks, that's a fair point - I created a new PR (#247), let me know if that makes sense!

**Pull request merged**
