### PR TITLE
Add dotnetify-reactjs sample.

### PR DESCRIPTION
**Pull request by SherifRefaat**
#166

### CODE REVIEW

**Comment by SherifRefaat** [comment]
@dodyg Check now after applying your comments.

**Comment by dodyg** [comment]
Thanks!

**Comment by dodyg** [comment]
@SherifRefaat  please write the description of the sample.

I've moved the sample here https://github.com/dodyg/practical-aspnetcore/tree/master/projects/signalr/dotnetify-reactjs and upgraded it to 2.2.

**Comment by SherifRefaat** [comment]
@dodyg I can't find a suitable section to put the sample. Please advise.

**Comment by SherifRefaat** [comment]
@dodyg Look at this effort: https://github.com/dodyg/practical-aspnetcore/pull/173

**Pull request merged**
