### PR TITLE
Added two Razor Pages examples

### PR DESCRIPTION
**Pull request by lukiasz**
Two examples:

First one (razor-pages-basic) shows simplest usage of razor pages in two flawors - with codebehind inlined in view file and in a separate file.

Second one (razor-pages-mvc) shows how basic operations (create, edit, list and one custom action) can be implemented both in mvc and in razor pages. It's a little more complex and I wonder whether it'll fit into overall project design.

What do you think about them?

Regards,

### CODE REVIEW

**Comment by dodyg** [comment]
* Merge Startup.cs and Program.cs to Program.cs.

**Comment by dodyg** [comment]
Actually it'll be faster if I do the splitting :) 

Thanks

**Comment by dodyg** [comment]
Actually your approach in the first sample is better than what I suggested. So I am going to keep the first and second one as is. Thanks.

**Comment by dodyg** [comment]
The first sample is added to the readme

**Comment by lukiasz** [comment]
I'm glad you like it and I hope it'll helpful for people learning these concepts :-) Sorry for forgotting adding README entries for them.

**Comment by dodyg** [comment]
I am learning from your samples. I always heard about the in memory database but I never thought that it would be perfect for sample projects. Brilliant. I haven't check Razor Pages until I reviewed your samples.

**Pull request merged**
