### PR TITLE
Extension methods

### PR DESCRIPTION
**Pull request by lfmundim**
Add a small sample regarding extension methods, a rather useful and pretty feature of C#

Note: motivated by #hacktoberfest

### CODE REVIEW

**Comment by dodyg** [comment]
Thanks for the submission. This is not a relevant sample unfortunately. Demonstrating C# feature isn't the goal of this repository.

**Comment by lfmundim** [comment]
> Thanks for the submission. This is not a relevant sample unfortunately. Demonstrating C# feature isn't the goal of this repository.

bummer :/ can it be approved for hacktoberfest though?

also, do you think sampling HTTP Requests using RestEase is a relevant sample? I could do that

**Comment by dodyg** [comment]
> bummer :/ can it be approved for hacktoberfest though?

Unfortunately I can't. This sample is simply not relevant to this repo. 

https://github.com/canton7/RestEase isn't really an ASP.NET Core project. 

If you are looking for an idea, you can check out the issues here https://github.com/dodyg/practical-aspnetcore/issues.

**Comment by lfmundim** [comment]
> https://github.com/canton7/RestEase isn't really an ASP.NET Core project.

It surely does work with .NET Core though, as I have used it many times on previous projects.

I will however take a look at the issues

**Comment by dodyg** [comment]
@lfmundim ok then you can create a sample for RestEase.

**Pull request closed without merging**
